services:
  nextjs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: converse-app
    pull_policy: build
    restart: always
    # ports:
    #   - 3000:3000
    env_file:
      - stack.env
    labels:
      # Traefik configuration discovery
      # https://doc.traefik.io/traefik/providers/docker/#routing-configuration-with-labels
      - "traefik.enable=true"
      - "traefik.http.middlewares.converse-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.converse-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.converse-http.middlewares=converse-redirect"
      - "traefik.http.routers.converse-http.rule=Host(`converse.docchula.com`)"
      - "traefik.http.routers.converse-http.entrypoints=web"
      - "traefik.http.routers.converse-https.rule=Host(`converse.docchula.com`)"
      - "traefik.http.routers.converse-https.entrypoints=websecure"
      - "traefik.http.routers.converse-https.tls.certresolver=leresolver"
      - "traefik.http.services.converse-https.loadbalancer.server.port=3000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:3000/api/up" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    #   start_interval: 5s